version: '3'
services:
  node:
    build: ./docker/node
    volumes:
      - app-volume:/app
    tty: true

  nginx:
    image: nginx
    volumes:
      - app-volume:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - node
volumes:
    app-volume: